### ISSUE TITLE
I don't understand J6

### ISSUE THREAD

**Issue by gcl8a** [WPIRoboticsEngineering/ZenDriver#2]
Isn't this the 2x header? I thought it was going to just breakout the pins, but it looks like one side holds the Thing and the other the DEV board. I must be missing something?

**Comment by acamilo** [comment]
This is there to make the footprint a little more compact.

The board is pushed up right to the plastic on the romi. 
You can only add PTH components in very specific places on the back where there are cutouts in the plastic.
I can't raise the board because the headers for the encoders don't give me any room.
I'm limited to sticking the module towards the front of the board where the headers should go.

This is how the boards are attatched.
![image](https://user-images.githubusercontent.com/2826967/94099199-5ea7e680-fdf8-11ea-9661-e65f6231c3ed.png)

now that i look at it, something is wrong with the pinout, need to fix that.
